### ISSUE TITLE
Eliminar scroll horizontal en web doc

### ISSUE THREAD

**Issue by jaicab** [carloscabo/gmapz#1]
Hay una clase `.row` que aplicas en contenedores de ancho completo y causan un scroll horizontal, al menos en OSX.

**Comment by carloscabo** [comment]
Esto tb lo tengo que mirar. He usado bootstrap para no perder mucho tiempo maquetando la ayuda :D

**Comment by carloscabo** [comment]
Creo que esto etá solucionado. Era una clase del bootstrap que me metía un margin negativo. Si lo ves OK lo cierro.

**Comment by jaicab** [comment]
Ahora está perfecto :+1:
